[package]
name = "cryptography"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1.1"
rand = "0.8.5"
secp256k1 = {version = "0.30.0", features = ["rand", "hashes"]}
sha256 = "1.5.0"
